logging:
  level:
    '[org.springframework.web]': debug

server:  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/worlddb    username: postgres
    password: password
  jpa:    hibernate:      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: postgresql
  