server:  port: 8082

logging:
  level:
    '[org.springframework.web]': debug
    
spring:  datasource:
    url: jdbc:postgresql://localhost:5432/colleagedb    username: postgres
    password: password
  jpa:    hibernate:      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: postgresql